### ISSUE TITLE
Fix "Resources" dropdown

### ISSUE THREAD

**Issue by neha26pp** [neha26pp/website.io#16]
In the dropdown, include the following links

- [x] https://github.com/neha26pp/website.io.git (link to this repo)

- [x]  https://student.worldcampus.psu.edu/content/student-organization-and-interest-group-submission-form (link to interest form to join the org)

**Comment by JaredD-SWENG** [comment]
This fix was applied - [https://stackoverflow.com/questions/62298361/bootstrap-dropdown-not-working-in-angular](url)
Finalizing couple more changes to dropdown before commiting
