### ISSUE TITLE
Choose a formatter

### ISSUE THREAD

**Issue by lwestfall** [neha26pp/website.io#7]
Formatters will automatically clean up your code to some predetermined set of rules, for example adding spaces where you'd want them. I recommend that we choose a formatter to agree to start using, so that our files are formatted consistently.

For typescript project (which Angular projects are), a really good one is called Prettier. You can read more about it here: https://prettier.io/

If anyone has any other suggestions, please comment!

**Comment by neha26pp** [comment]
sounds good! Prettier looks like a really good option
