### ISSUE TITLE
Move contents of web-design up to root

### ISSUE THREAD

**Issue by lwestfall** [neha26pp/website.io#8]
I think the current directory structure is causing a little bit of confusion among some of our less experienced folks. It's an extra step to change directories down to `./web-design`, additionally the readme.md is best to put at the root so it's the first thing you see in Github. The extra layer in the directory structure doesn't seem to be offering us any benefits as far as I can tell.

Additionally (this could be a separate issue, but I'll leave it here for now as it could be combined in the proposal above): I think we should add the .idea directory to the .gitignore. This is a Jetbrains IDE specific directory, and very often you don't want these in source control (unless we decided to all adhere to the same IDE and all of the options set therein).

I'd like to get an agreement from @neha26pp and @TarenLewis before anyone takes action on this. Let's discuss it here, and if there is consensus then this could make a great first issue for someone! I'd be happy to guide that person through this if they aren't sure where to start.

**Comment by neha26pp** [comment]
yes I think finding the correct directory adhering to the current structure is causing a lot of confusion.
I think what you suggested would be great

**Comment by TarenLewis** [comment]
This seems like a good issue to practice submitting a PR. I approve of both of these changes

**Comment by lwestfall** [comment]
Cool! Regarding the .gitignore, I noticed that the one in web-design already contains .idea, so that doesn't need to be a separate step. Bringing all of the contents up to the root and then running `git rm -r .idea` from the root should be enough.

**Dear Contributor - Read This**

Take a look at the description in the first comment and take a stab at it, and then submit a PR! If you get stuck, make a comment here or ask in discord. Read [Contributing.md](https://github.com/neha26pp/website.io/blob/master/web-design/Contributing.md) if you don't know where to start.
